[tool.black]
line-length = 110
exclude = '''
/(
  | env
)/
'''

[tool.isort]
force_grid_wrap = 0
include_trailing_comma = true
line_length = 110
multi_line_output = 3
use_parentheses = true
skip_glob = "env"
